name: CI/CD Deployment

on:
  push:
    branches: [ "dev" ] # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 1. Build
        # Perform build and tests as required
        run: mvn clean package -Dmaven.test.skip=true

      - name: 2. Build Docker Image
        # Build the API Docker image
        run: sudo docker build -t bookshop-api .

      - name: 3. Deploy to Server via SSH
        # Deploy using SSH [cite: 79, 80]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/bookshop
            git pull origin main
            docker compose up -d --build
            
            echo "Waiting for Spring Boot on port 8088..."
            sleep 40 
            
            # Use 8088 here because this command runs on the HOST
            curl -f http://localhost:8088/api/public/categories || (docker logs bookshop-api && exit 1)